# Practical session 1 : R script

# Goal: Load FastQC results and display summary tables and plots

# Load the fastqcr package
# fastqcr : R package to (run and) load FastQC files
# Documentation : http://www.sthda.com/english/wiki/fastqcr-an-r-package-facilitating-quality-controls-of-sequencing-data-for-large-numbers-of-samples
library(fastqcr)

# Adapt the path between double quotes as needed
folderRes <-  "./Data"

# Step 1: Load the zip files generated by FastQC
# fastqcr will look into a folder for zip files (outputs from FastQC)
qc <- qc_aggregate(folderRes)

# Step 2 : Display global summaries of what was loaded

# Content of the object where all the information was loaded by fastqcr
qc

# General statistics for all samples
qc_stats(qc)

# Tests performed by FastQC on all samples
summary(qc)

# Step 3 : focus on one sample

# List all zip files in the specified folder
all.results <- list.files(path=folderRes, pattern="*.zip", full.names=TRUE)


# Show one of the plots
qc_plot(all.results[1], "Per base sequence quality")

